routes/web.php
<?php

//Route::get('/', 'NewsController@index');

Route::get('/', 'WeatherController@index');
Route::get('/gis', 'WeatherController@gis');


Route::get('/news/{id}', 'NewsController@show');
Route::get('/news_short/{id}', 'NewsController@show_short');

Route::get('/news_short_50/{id}', 'NewsController@show_short_50');
Route::get('/news_50/{id}', 'NewsController@show_50');

Route::get('/news_click/{id}', 'NewsController@click');
Route::get('/news_click_full/{id}', 'NewsController@click_full');

//Route::get('/tizers', 'TizerController@index');
//Route::get('/news50', 'NewsController@news');
Route::get('/tizers/{id}', 'TizerController@show');
//Route::get('/tizers/test/{id}/{click_by}', 'TizerController@click_test');
//Route::get('/stat/heare/{id}', 'StatController@heare');

//Route::get('/users_guide', 'NewsController@users_guide');
//Route::get('/users_coockie', 'NewsController@users_coockie');
//Route::get('/day_news', 'NewsController@random');
//Route::get('/social_news', 'NewsController@random');
//Route::get('/actions', 'NewsController@random');

//Route::get('/testpeople', 'NewsController@testpeople');
//Route::get('/testvue', 'NewsController@testvue');
//Route::get('/test/stat', 'TestController@stat');

//Route::get('/landing', 'LandingController@index')->name('landing');
Route::get('/showimage/{img}', 'NewsController@showimage')->name('showimage');

// WEB Push
//Route::post('/subscriber', 'SubController@subscriber')->middleware("cors");
Auth::routes(['register' => false]);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Scripts
    //Route::delete('scripts/destroy', 'ScriptsController@massDestroy')->name('scripts.massDestroy');
    //Route::resource('scripts', 'ScriptsController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Templates
    Route::delete('templates/destroy', 'TemplatesController@massDestroy')->name('templates.massDestroy');
    Route::resource('templates', 'TemplatesController');

    // Domains
    Route::delete('domains/destroy', 'DomainsController@massDestroy')->name('domains.massDestroy');
    Route::post('domains/media', 'DomainsController@storeMedia')->name('domains.storeMedia');
    Route::resource('domains', 'DomainsController');

    // Sources
    Route::delete('sources/destroy', 'SourcesController@massDestroy')->name('sources.massDestroy');
    Route::resource('sources', 'SourcesController');

    // News
    Route::delete('news/destroy', 'NewsController@massDestroy')->name('news.massDestroy');
    Route::get('news/null/{id}', 'NewsController@null')->name('news.null');
    Route::post('news/media', 'NewsController@storeMedia')->name('news.storeMedia');
    Route::post('news/ckmedia', 'NewsController@storeCKEditorImages')->name('news.storeCKEditorImages');
    Route::resource('news', 'NewsController', ['except' => ['show']]);

    // Tizers
    Route::delete('tizers/destroy', 'TizersController@massDestroy')->name('tizers.massDestroy');
    Route::get('tizers/null/{id}', 'TizersController@null')->name('tizers.null');
    Route::get('tizers/active', 'TizersController@active')->name('tizers.active');
    Route::post('tizers/media', 'TizersController@storeMedia')->name('tizers.storeMedia');
    Route::post('tizers/ckmedia', 'TizersController@storeCKEditorImages')->name('tizers.storeCKEditorImages');
    Route::resource('tizers', 'TizersController');

    // tizers-test
    Route::resource('tizers-test', 'TizersTestController');
    Route::get('tizerstest/active', 'TizersTestController@active')->name('tizerstest.active');
    Route::get('tizerstest/applyb', 'TizersTestController@applyb')->name('tizerstest.applyb');

    // TizersResult
    Route::resource('tizers-result', 'TizersResultController');

    // NewsResult
    Route::resource('news-result', 'NewsResultController');

    // TizersStatResult
    Route::resource('tizers-stat', 'TizersStatController');

    // Stats
    Route::resource('stats', 'StatsController');

    
    /// PUSH ROUTERS ///
    // Push templates
    Route::resource('push-templates', 'PushTemplatesController', ['except' => ['show']]);
    Route::delete('push-templates/destroy', 'PushTemplatesController@massDestroy')->name('push-templates.massDestroy');

    // Push clients
    Route::resource('push-clients', 'PushClientsController', ['except' => ['show']]);

    // Push  
    Route::resource('pushes', 'PushController', ['except' => ['show', 'index', 'create']]);
    Route::get('pushes/{push_template}', ['as' => 'pushes.index', 'uses' => 'PushController@index']);
    Route::get('pushes/create/{template}', ['as' => 'pushes.create', 'uses' => 'PushController@create']);
    Route::delete('pushes/destroy', 'PushController@massDestroy')->name('pushes.massDestroy');
    Route::post('pushes/media', 'PushController@storeMedia')->name('pushes.storeMedia');
    Route::get('pushes/status/{push}/{status}', 'PushController@status')->name('pushes.status');
    
});

app/Source.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;

class Source extends Model
{
    use SoftDeletes;


    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',        
        'utms',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function scripts()
    {
        return $this->belongsToMany(Script::class);
    }

    static function getSource(Request $request) {
        if ( $request->has('sid8') ) {            
            return Source::find($request->get('sid8'));
        }
        
        return false;
    }
}

app/Http/Controllers/Admin/SourcesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreSourceRequest;
use App\Http\Requests\UpdateSourceRequest;
use App\Script;
use App\Source;
use Gate;

use Symfony\Component\HttpFoundation\Response;

class SourcesController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('template_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $sources = Source::all();

        return view('admin.sources.index', compact('sources'));
    }

    public function create()
    {
        abort_if(Gate::denies('template_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $scripts = Script::all()->pluck('title', 'id');
        return view('admin.sources.create', compact('scripts'));
    }

    public function store(StoreSourceRequest $request)
    {
        $source = Source::create($request->all());
        $source->scripts()->sync($request->input('scripts', []));

        return redirect()->route('admin.sources.index');
    }

    public function edit(Source $source)
    {
        abort_if(Gate::denies('template_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $scripts = Script::all()->pluck('title', 'id');

        $source->load('scripts');

        return view('admin.sources.edit', compact('scripts', 'source'));
    }

    public function update(UpdateSourceRequest $request, Source $source)
    {
        $source->update($request->all());
        $source->scripts()->sync($request->input('scripts', []));

        return redirect()->route('admin.sources.index');
    }

    public function show(Source $source)
    {
        abort_if(Gate::denies('template_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $source->load('scripts');

        return view('admin.templates.show', compact('source'));
    }

    public function destroy(Source $source)
    {
        abort_if(Gate::denies('template_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $source->delete();

        return back();
    }

    public function massDestroy(MassDestroyTemplateRequest $request)
    {
        Source::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/sources/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        Создать источник
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.sources.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="title">Заголовок</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
            </div>

            <div class="form-group">
                <label class="required" for="utms">Макросы</label>
                <input class="form-control {{ $errors->has('utms') ? 'is-invalid' : '' }}" type="text" name="utms" id="utms" value="{{ old('utms', '') }}" required>
                @if($errors->has('utms'))
                    <span class="text-danger">{{ $errors->first('utms') }}</span>
                @endif
            </div>

            <div class="form-group">
                <label for="scripts">Скрипты</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('scripts') ? 'is-invalid' : '' }}" name="scripts[]" id="scripts" multiple>
                    @foreach($scripts as $id => $scripts)
                        <option value="{{ $id }}" {{ in_array($id, old('scripts', [])) ? 'selected' : '' }}>{{ $scripts }}</option>
                    @endforeach
                </select>
                @if($errors->has('scripts'))
                    <span class="text-danger">{{ $errors->first('scripts') }}</span>
                @endif
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/sources/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        Редактировать источник
    </div>

    <div class="card-body">  
        <form method="POST" action="{{ route("admin.sources.update", [$source->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="title">Заголовок</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $source->title) }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
            </div>

            <div class="form-group">
                <label class="required" for="utms">Макросы</label>
                <input class="form-control {{ $errors->has('utms') ? 'is-invalid' : '' }}" type="text" name="utms" id="utms" value="{{ old('utms', $source->utms) }}" required>
                @if($errors->has('utms'))
                    <span class="text-danger">{{ $errors->first('utms') }}</span>
                @endif
            </div>

            <div class="form-group">
                <label for="scripts">Скрипты</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('scripts') ? 'is-invalid' : '' }}" name="scripts[]" id="scripts" multiple>
                    @foreach($scripts as $id => $script)
                        <option value="{{ $id }}" {{ (in_array($id, old('scripts', [])) || $source->scripts->contains($id)) ? 'selected' : '' }}>{{ $script }}</option>
                    @endforeach
                </select>
                @if($errors->has('scripts'))
                    <span class="text-danger">{{ $errors->first('scripts') }}</span>
                @endif
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/sources/index.blade.php
@extends('layouts.admin')
@section('content')
@can('template_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.sources.create") }}">
                {{ trans('global.add') }} Источник
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        Источники {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Source">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.template.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.template.fields.title') }}
                        </th>
                        <th>
                            Скрипты
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($sources as $key => $source)
                        <tr data-entry-id="{{ $source->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $source->id ?? '' }}
                            </td>
                            <td>
                                {{ $source->title ?? '' }}
                            </td>
                            <td>
                                @foreach($source->scripts as $key => $item)
                                    <span class="badge badge-info">{{ $item->title }}</span>
                                @endforeach
                            </td>
                            <td>
                                @can('template_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.sources.edit', $source->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @if ( $source->id !== 1 )
                                @can('template_delete')
                                    <form action="{{ route('admin.sources.destroy', $source->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                                @endif  

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('template_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.sources.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Source:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection