routes/web.php
<?php

//Route::get('/', 'NewsController@index');

Route::get('/', 'WeatherController@index');
Route::get('/gis', 'WeatherController@gis');


Route::get('/news/{id}', 'NewsController@show');
Route::get('/news_short/{id}', 'NewsController@show_short');

Route::get('/news_short_50/{id}', 'NewsController@show_short_50');
Route::get('/news_50/{id}', 'NewsController@show_50');

Route::get('/news_click/{id}', 'NewsController@click');
Route::get('/news_click_full/{id}', 'NewsController@click_full');

//Route::get('/tizers', 'TizerController@index');
//Route::get('/news50', 'NewsController@news');
Route::get('/tizers/{id}', 'TizerController@show');
//Route::get('/tizers/test/{id}/{click_by}', 'TizerController@click_test');
//Route::get('/stat/heare/{id}', 'StatController@heare');

//Route::get('/users_guide', 'NewsController@users_guide');
//Route::get('/users_coockie', 'NewsController@users_coockie');
//Route::get('/day_news', 'NewsController@random');
//Route::get('/social_news', 'NewsController@random');
//Route::get('/actions', 'NewsController@random');

//Route::get('/testpeople', 'NewsController@testpeople');
//Route::get('/testvue', 'NewsController@testvue');
//Route::get('/test/stat', 'TestController@stat');

//Route::get('/landing', 'LandingController@index')->name('landing');
Route::get('/showimage/{img}', 'NewsController@showimage')->name('showimage');

// WEB Push
//Route::post('/subscriber', 'SubController@subscriber')->middleware("cors");
Auth::routes(['register' => false]);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Scripts
    //Route::delete('scripts/destroy', 'ScriptsController@massDestroy')->name('scripts.massDestroy');
    //Route::resource('scripts', 'ScriptsController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Templates
    Route::delete('templates/destroy', 'TemplatesController@massDestroy')->name('templates.massDestroy');
    Route::resource('templates', 'TemplatesController');

    // Domains
    Route::delete('domains/destroy', 'DomainsController@massDestroy')->name('domains.massDestroy');
    Route::post('domains/media', 'DomainsController@storeMedia')->name('domains.storeMedia');
    Route::resource('domains', 'DomainsController');

    // Sources
    Route::delete('sources/destroy', 'SourcesController@massDestroy')->name('sources.massDestroy');
    Route::resource('sources', 'SourcesController');

    // News
    Route::delete('news/destroy', 'NewsController@massDestroy')->name('news.massDestroy');
    Route::get('news/null/{id}', 'NewsController@null')->name('news.null');
    Route::post('news/media', 'NewsController@storeMedia')->name('news.storeMedia');
    Route::post('news/ckmedia', 'NewsController@storeCKEditorImages')->name('news.storeCKEditorImages');
    Route::resource('news', 'NewsController', ['except' => ['show']]);

    // Tizers
    Route::delete('tizers/destroy', 'TizersController@massDestroy')->name('tizers.massDestroy');
    Route::get('tizers/null/{id}', 'TizersController@null')->name('tizers.null');
    Route::get('tizers/active', 'TizersController@active')->name('tizers.active');
    Route::post('tizers/media', 'TizersController@storeMedia')->name('tizers.storeMedia');
    Route::post('tizers/ckmedia', 'TizersController@storeCKEditorImages')->name('tizers.storeCKEditorImages');
    Route::resource('tizers', 'TizersController');

    // tizers-test
    Route::resource('tizers-test', 'TizersTestController');
    Route::get('tizerstest/active', 'TizersTestController@active')->name('tizerstest.active');
    Route::get('tizerstest/applyb', 'TizersTestController@applyb')->name('tizerstest.applyb');

    // TizersResult
    Route::resource('tizers-result', 'TizersResultController');

    // NewsResult
    Route::resource('news-result', 'NewsResultController');

    // TizersStatResult
    Route::resource('tizers-stat', 'TizersStatController');

    // Stats
    Route::resource('stats', 'StatsController');

    
    /// PUSH ROUTERS ///
    // Push templates
    Route::resource('push-templates', 'PushTemplatesController', ['except' => ['show']]);
    Route::delete('push-templates/destroy', 'PushTemplatesController@massDestroy')->name('push-templates.massDestroy');

    // Push clients
    Route::resource('push-clients', 'PushClientsController', ['except' => ['show']]);

    // Push  
    Route::resource('pushes', 'PushController', ['except' => ['show', 'index', 'create']]);
    Route::get('pushes/{push_template}', ['as' => 'pushes.index', 'uses' => 'PushController@index']);
    Route::get('pushes/create/{template}', ['as' => 'pushes.create', 'uses' => 'PushController@create']);
    Route::delete('pushes/destroy', 'PushController@massDestroy')->name('pushes.massDestroy');
    Route::post('pushes/media', 'PushController@storeMedia')->name('pushes.storeMedia');
    Route::get('pushes/status/{push}/{status}', 'PushController@status')->name('pushes.status');
    
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

use Illuminate\Support\Facades\Cache;

use App\Traits\RowsTrait;
use Illuminate\Support\Facades\DB;

use Intervention\Image\Gd\Decoder;

class News extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait, RowsTrait;

    public $table = 'news';

    protected $appends = [
        'image',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'desc',
        'title',
        'country',
        'cats',
        'views',
        'clicks',
        'short_desc',
        'created_at',
        'updated_at',
        'deleted_at',
        'color',
        'is_razgon',
    ];

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(367)->height(268);
    }

    public function getImageAttribute()
    {
        $file = $this->getMedia('image')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }

    public function viewUp($template_id){
        $templTizerV = new TemplateNewsViews();
        $templTizerV->news_id = $this->id;
        $templTizerV->template_id = $template_id;
        $templTizerV->save();

        $ct = TemplateNews::where('template_id', $template_id)
            ->where('news_id', $this->id)->first();
        if ( !$ct ) {
            $ct = new TemplateNews();
            $ct->news_id = $this->id;
            $ct->template_id = $template_id;
            $ct->views = 0;
            $ct->clicks = 0;
            $ct->save();
        }

        $ct->increment('views');
    }

    public function clickUp($template_id){
        $templTizerC = new TemplateNewsClick();
        $templTizerC->news_id = $this->id;
        $templTizerC->template_id = $template_id;
        $templTizerC->save();


        $ct = TemplateNews::where('template_id', $template_id)
            ->where('news_id', $this->id)->first();
        if ( !$ct ) {
            $ct = new TemplateNews();
            $ct->news_id = $this->id;
            $ct->template_id = $template_id;
            $ct->views = 0;
            $ct->clicks = 0;
            $ct->save();
        }

        $ct->increment('clicks');
    }    

    static function algo($params = []) {

        $collect = self::select(DB::raw('`news`.*, IFNULL(`views`, 0) as `views`, IFNULL(`clicks`, 0) as `clicks`'))
            ->from('news') 
            ->leftJoin('template_news', 'news.id', '=', 'template_news.news_id')
            ->where(DB::raw('IFNULL(`template_id`, '.$params['template_id'].')'), $params['template_id'] );

        if ( !isset($params['razgon']) ) {
            if ( isset($params['random']) ) {
                $collect->orderBy(DB::raw('rand()')); 
            } else {
                $collect->orderBy(DB::raw('clicks/views'), 'DESC'); 
            }
            
        } else  {
            $collect->orderBy(DB::raw('clicks/views'), 'DESC');
            $template = Template::find($params['template_id']);
            $collect->where('is_razgon', true );
            $collect->where('views', "<", $template->news_boost_val ); 
        }      
        
        // обработка параметра excludeIds
        if ( isset($params['excludeIds']) ) {
            sort($params['excludeIds']);            
            $collect->whereNotIn('news.id', $params['excludeIds']);
        }

        if ( isset($params['country']) ) {
            $collect->where('country', $params['country']);
        }

        if ( isset($params['cats']) ) {
            $collect->where(function($q) use ($params) {
                foreach ($params['cats'] as $cat_id) {
                    $q->orWhereRaw('FIND_IN_SET(?, cats)', $cat_id);
                }                                  
            });  
        }
        
        return $collect;
    }


    public function getUrl($template_id=1, $link = '', $cont = '/news/') {
        $this->viewUp($template_id);
        
        if ( $link != '' ) {
            return $cont . $this->id . '?' . $link;
        }
        
        return $cont . $this->id;
    }

    public function getCtr() {
        return round($this->views > 0 ? $this->clicks / $this->views : null, 3) * 100;
    }

    public function getPrior() {
        return $this->getCtr();
    }

    public function getTitle() {
        return $this->title; 
    }

    public function getImage() {
        return  $this->image; 
    }

    public function getImageThumb() {
        $keyThumb = $_SERVER['HTTP_HOST'] . "-thumb-for-mews-id-" . $this->id;
        if ( true || !$url = Cache::get($keyThumb) ) {
            $url = $this->getImage() ?  $this->getImage()->getUrl('thumb') : false;              
            Cache::put($keyThumb, $url, 3600);
        }
        return $url;
    }

    public function getRGBText() {
        return !Is_null($this->color) ?  $this->color : '101, 86, 116'; 
    }

    public function getColor($image_path) {                
        $dec = new Decoder();
        $img = $dec->initFromPath($image_path)->getCore();
        $w = imagesx($img);
        $h = imagesy($img);
        $r = $g = $b = 0;

        for($y = 0; $y < $h; $y++) {
            for($x = 0; $x < $w; $x++) {
                $rgb = imagecolorat($img, $x, $y);
                $r += $rgb >> 16;
                $g += $rgb >> 8 & 255;
                $b += $rgb & 255;
            }
        }            
        
        $pxls = $w * $h;

        $r = round($r / $pxls);
        $g = round($g / $pxls);
        $b = round($b / $pxls);
        
        return $r . ', ' . $g . ', ' . $b;
    }
}

app/Http/Controllers/Admin/TizersResultController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyTizerRequest;
use App\Http\Requests\StoreTizerRequest;
use App\Http\Requests\UpdateTizerRequest;
use App\Template;
use App\Tizer;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class TizersResultController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('tizer_result_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $templates = Template::all();
        $current_template = isset($_GET['current_template']) ? intval($_GET['current_template']) : 1;
        $params = [];

        $params['template_id'] = $current_template;

        $countries = $this->countries;
        $current_country = isset($_GET['current_country']) ? $_GET['current_country'] : "Россия";

        $params['country'] = $current_country;

        
        $params['cats'] = [];
        $templateFound = Template::find($current_template);
        $templateFound->load('categories');
        foreach ($templateFound->categories as $c) {
            $params['cats'][] = $c['id'];
        } 

    
        $tizers = Tizer::algo($params)->get();

        return view('admin.tizers-result.index', compact('tizers', 'countries', 'templates', 'current_template', 'current_country'));
    }

    public function mix()
    {
        abort_if(Gate::denies('tizer_result_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');     
        $templates = Template::all();
        $current_template = isset($_GET['current_template']) ? intval($_GET['current_template']) : 1;
        $params = [];

        $params['template_id'] = $current_template;

        $countries = $this->countries;
        $current_country = isset($_GET['current_country']) ? $_GET['current_country'] : "Россия";
        $params['country'] = $current_country;
        
        $params['cats'] = [];
        $templateFound = Template::find($current_template);
        $templateFound->load('categories');
        foreach ($templateFound->categories as $c) {
            $params['cats'][] = $c['id'];
        } 

    
        $tizers = Tizer::algo($params)->get();
        $news = News::algo($params)->get();
        $items = [];

        return view('admin.tizers-result.mix', compact('items', 'countries', 'templates', 'current_template', 'current_country'));
    }

    
}

resources/views/admin/tizers-result/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.tizer.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tizers.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="image">{{ trans('cruds.tizer.fields.image') }}</label>
                <div class="needsclick dropzone {{ $errors->has('image') ? 'is-invalid' : '' }}" id="image-dropzone">
                </div>
                @if($errors->has('image'))
                    <span class="text-danger">{{ $errors->first('image') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.tizer.fields.image_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="title">{{ trans('cruds.tizer.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}" >
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.tizer.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="ext_link">{{ trans('cruds.tizer.fields.ext_link') }}</label>
                <input class="form-control {{ $errors->has('ext_link') ? 'is-invalid' : '' }}" type="text" name="ext_link" id="ext_link" value="{{ old('ext_link', '') }}" required>
                @if($errors->has('ext_link'))
                    <span class="text-danger">{{ $errors->first('ext_link') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.tizer.fields.ext_link_helper') }}</span>
            </div>
            <div class="form-group">
                <label  for="desc">{{ trans('cruds.tizer.fields.desc') }}</label>
                <input class="form-control {{ $errors->has('desc') ? 'is-invalid' : '' }}" type="text" name="desc" id="desc" value="{{ old('desc', '') }}">
                @if($errors->has('desc'))
                    <span class="text-danger">{{ $errors->first('desc') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.tizer.fields.desc_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="required" for="country">{{ trans('cruds.tizer.fields.country') }}</label>
               
                <select class="form-control select2 {{ $errors->has('country') ? 'is-invalid' : '' }}" name="country" id="country" required>
                    <option value="">-- Необходимо выбрать --</option>
                    @foreach($countries as $cat)
                        <option value="{{ $cat }}">{{ $cat }}</option>
                    @endforeach
                </select>
                @if($errors->has('country'))
                    <span class="text-danger">{{ $errors->first('country') }}</span>
                @endif                
            </div>

            <div class="form-group">
                <label class="required" for="categories">{{ trans('cruds.tizer.fields.category_id') }}</label>
               
                <select class="form-control select2 {{ $errors->has('category_id') ? 'is-invalid' : '' }}" name="category_id" id="category_id" required>
                    <option value="">-- Необходимо выбрать --</option>
                    @foreach($categories as $id => $cat)
                        <option value="{{ $id }}">{{ $cat }}</option>
                    @endforeach
                </select>
                @if($errors->has('category_id'))
                    <span class="text-danger">{{ $errors->first('category_id') }}</span>
                @endif
                
            </div>

            <div class="form-group">
                <label for="aprove">{{ trans('cruds.tizer.fields.aprove') }}</label>
                <input class="form-control {{ $errors->has('aprove') ? 'is-invalid' : '' }}" type="number" name="aprove" id="aprove" value="{{ old('aprove') }}" step="0.01">
                @if($errors->has('aprove'))
                    <span class="text-danger">{{ $errors->first('aprove') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.tizer.fields.aprove_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="price">{{ trans('cruds.tizer.fields.price') }}</label>
                <input class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" name="price" id="price" value="{{ old('price') }}" step="0.01">
                @if($errors->has('price'))
                    <span class="text-danger">{{ $errors->first('price') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.tizer.fields.price_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    Dropzone.options.imageDropzone = {
    url: '{{ route('admin.tizers.storeMedia') }}',
    maxFilesize: 20, // MB
    acceptedFiles: '.jpeg,.jpg,.png,.gif',
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 20,
      width: 4096,
      height: 4096
    },
    success: function (file, response) {
      $('form').find('input[name="image"]').remove()
      $('form').append('<input type="hidden" name="image" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="image"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($tizer) && $tizer->image)
      var file = {!! json_encode($tizer->image) !!}
          this.options.addedfile.call(this, file)
      this.options.thumbnail.call(this, file, '{{ $tizer->image->getUrl('thumb') }}')
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="image" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
    error: function (file, response) {
        if ($.type(response) === 'string') {
            var message = response //dropzone sends it's own error messages in string
        } else {
            var message = response.errors.file
        }
        file.previewElement.classList.add('dz-error')
        _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
        _results = []
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            node = _ref[_i]
            _results.push(node.textContent = message)
        }

        return _results
    }
}
</script>
@endsection

resources/views/admin/tizers-result/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        Выдача тизеров 
    </div>

    <div class="card-body">
        
        <form id="templ_form">
            <div class="row">
            <div class="col-md-6">
            <select name='current_template' id="current_template" class="select2">
            @foreach($templates as  $templ)
                <option value="{{$templ->id}}" @if( $current_template==$templ->id ) selected=selected @endif>{{$templ->title}}</option>
            @endforeach
            </select>
            </div>
            <div class="col-md-6">
            <select name='current_country' id="current_country" class="select2">
            @foreach($countries as  $c)
                <option value="{{$c}}" @if( $current_country==$c ) selected=selected @endif>{{$c}}</option>
            @endforeach
            </select>
            </div>
            </div>
        </form>
        <br>
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatat">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.image') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.title') }}
                        </th>
                        
                        <th>
                            {{ trans('cruds.tizer.fields.views') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.clicks') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.ctr') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.aprove') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.price') }}
                        </th>
                        <th>
                            {{ trans('cruds.tizer.fields.prior') }}
                        </th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach($tizers as $key => $tizer)
                        <tr data-entry-id="{{ $tizer->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $tizer->id ?? '' }}
                            </td>
                            <td>
                                @if($tizer->image)
                                    <a href="{{ $tizer->image->getUrl() }}" target="_blank">
                                        <img src="{{ $tizer->image->getUrl('thumb') }}" width="50px" height="50px">
                                    </a>
                                @endif
                            </td>
                            <td>
                                {{ $tizer->title ?? '' }}
                            </td>
                           
                            <td>
                                {{ $tizer->views ?? '' }}
                            </td>
                            <td>
                                {{ $tizer->clicks ?? '' }}
                            </td>
                            <td>
                                {{ $tizer->getCtr() ?? '' }}%
                            </td>
                            <td>
                                {{ $tizer->aprove ?? '' }}
                            </td>
                            <td>
                                {{ $tizer->price ?? '' }}
                            </td>
                            <td>
                                {{ $tizer->getPrior() ?? '' }}
                            </td>
                            

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
        $('#current_template, #current_country').on('change' , function(e) {
            form = $("#templ_form");
            form[0].submit()
        });



  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('tizer_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tizers.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Tizer:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/tizers-result/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.tizer.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tizers.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.id') }}
                        </th>
                        <td>
                            {{ $tizer->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.image') }}
                        </th>
                        <td>
                            @if($tizer->image)
                                <a href="{{ $tizer->image->getUrl() }}" target="_blank">
                                    <img src="{{ $tizer->image->getUrl('thumb') }}" width="50px" height="50px">
                                </a>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.title') }}
                        </th>
                        <td>
                            {{ $tizer->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.desc') }}
                        </th>
                        <td>
                            {{ $tizer->desc }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.views') }}
                        </th>
                        <td>
                            {{ $tizer->views }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.clicks') }}
                        </th>
                        <td>
                            {{ $tizer->clicks }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.aprove') }}
                        </th>
                        <td>
                            {{ $tizer->aprove }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tizer.fields.price') }}
                        </th>
                        <td>
                            {{ $tizer->price }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tizers.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection