routes/web.php
<?php

//Route::get('/', 'NewsController@index');

Route::get('/', 'WeatherController@index');
Route::get('/gis', 'WeatherController@gis');


Route::get('/news/{id}', 'NewsController@show');
Route::get('/news_short/{id}', 'NewsController@show_short');

Route::get('/news_short_50/{id}', 'NewsController@show_short_50');
Route::get('/news_50/{id}', 'NewsController@show_50');

Route::get('/news_click/{id}', 'NewsController@click');
Route::get('/news_click_full/{id}', 'NewsController@click_full');

//Route::get('/tizers', 'TizerController@index');
//Route::get('/news50', 'NewsController@news');
Route::get('/tizers/{id}', 'TizerController@show');
//Route::get('/tizers/test/{id}/{click_by}', 'TizerController@click_test');
//Route::get('/stat/heare/{id}', 'StatController@heare');

//Route::get('/users_guide', 'NewsController@users_guide');
//Route::get('/users_coockie', 'NewsController@users_coockie');
//Route::get('/day_news', 'NewsController@random');
//Route::get('/social_news', 'NewsController@random');
//Route::get('/actions', 'NewsController@random');

//Route::get('/testpeople', 'NewsController@testpeople');
//Route::get('/testvue', 'NewsController@testvue');
//Route::get('/test/stat', 'TestController@stat');

//Route::get('/landing', 'LandingController@index')->name('landing');
Route::get('/showimage/{img}', 'NewsController@showimage')->name('showimage');

// WEB Push
//Route::post('/subscriber', 'SubController@subscriber')->middleware("cors");
Auth::routes(['register' => false]);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Scripts
    //Route::delete('scripts/destroy', 'ScriptsController@massDestroy')->name('scripts.massDestroy');
    //Route::resource('scripts', 'ScriptsController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');

    // Templates
    Route::delete('templates/destroy', 'TemplatesController@massDestroy')->name('templates.massDestroy');
    Route::resource('templates', 'TemplatesController');

    // Domains
    Route::delete('domains/destroy', 'DomainsController@massDestroy')->name('domains.massDestroy');
    Route::post('domains/media', 'DomainsController@storeMedia')->name('domains.storeMedia');
    Route::resource('domains', 'DomainsController');

    // Sources
    Route::delete('sources/destroy', 'SourcesController@massDestroy')->name('sources.massDestroy');
    Route::resource('sources', 'SourcesController');

    // News
    Route::delete('news/destroy', 'NewsController@massDestroy')->name('news.massDestroy');
    Route::get('news/null/{id}', 'NewsController@null')->name('news.null');
    Route::post('news/media', 'NewsController@storeMedia')->name('news.storeMedia');
    Route::post('news/ckmedia', 'NewsController@storeCKEditorImages')->name('news.storeCKEditorImages');
    Route::resource('news', 'NewsController', ['except' => ['show']]);

    // Tizers
    Route::delete('tizers/destroy', 'TizersController@massDestroy')->name('tizers.massDestroy');
    Route::get('tizers/null/{id}', 'TizersController@null')->name('tizers.null');
    Route::get('tizers/active', 'TizersController@active')->name('tizers.active');
    Route::post('tizers/media', 'TizersController@storeMedia')->name('tizers.storeMedia');
    Route::post('tizers/ckmedia', 'TizersController@storeCKEditorImages')->name('tizers.storeCKEditorImages');
    Route::resource('tizers', 'TizersController');

    // tizers-test
    Route::resource('tizers-test', 'TizersTestController');
    Route::get('tizerstest/active', 'TizersTestController@active')->name('tizerstest.active');
    Route::get('tizerstest/applyb', 'TizersTestController@applyb')->name('tizerstest.applyb');

    // TizersResult
    Route::resource('tizers-result', 'TizersResultController');

    // NewsResult
    Route::resource('news-result', 'NewsResultController');

    // TizersStatResult
    Route::resource('tizers-stat', 'TizersStatController');

    // Stats
    Route::resource('stats', 'StatsController');

    
    /// PUSH ROUTERS ///
    // Push templates
    Route::resource('push-templates', 'PushTemplatesController', ['except' => ['show']]);
    Route::delete('push-templates/destroy', 'PushTemplatesController@massDestroy')->name('push-templates.massDestroy');

    // Push clients
    Route::resource('push-clients', 'PushClientsController', ['except' => ['show']]);

    // Push  
    Route::resource('pushes', 'PushController', ['except' => ['show', 'index', 'create']]);
    Route::get('pushes/{push_template}', ['as' => 'pushes.index', 'uses' => 'PushController@index']);
    Route::get('pushes/create/{template}', ['as' => 'pushes.create', 'uses' => 'PushController@create']);
    Route::delete('pushes/destroy', 'PushController@massDestroy')->name('pushes.massDestroy');
    Route::post('pushes/media', 'PushController@storeMedia')->name('pushes.storeMedia');
    Route::get('pushes/status/{push}/{status}', 'PushController@status')->name('pushes.status');
    
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function categoriesTemplates()
    {
        return $this->belongsToMany(Template::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Category;
use App\Http\Requests\StoreCategoryRequest;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CategoriesController extends Controller
{

    public function index()
    {
        abort_if(Gate::denies('category_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = Category::all();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        abort_if(Gate::denies('category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categories.create');
    }

    public function store(StoreCategoryRequest $request)
    {
        $category = Category::create($request->all());

        return redirect()->route('admin.categories.index');
    }

    public function edit(Category $category)
    {
        abort_if(Gate::denies('category_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.categories.edit', compact('category'));
    }

    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->route('admin.categories.index');
    }

    public function destroy(Category $category)
    {
        abort_if(Gate::denies('category_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $category->delete();

        return back();
    }

    public function massDestroy(MassDestroyCategoryRequest $request)
    {
        Category::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.category.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.categories.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="title">{{ trans('cruds.category.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.category.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.category.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.categories.update", [$category->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="title">{{ trans('cruds.category.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $category->title) }}" required>
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.category.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')
@section('content')
@can('category_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.categories.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.category.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.category.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Permission">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.category.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.category.fields.title') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($categories as $key => $category)
                        <tr data-entry-id="{{ $category->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $category->id ?? '' }}
                            </td>
                            <td>
                                {{ $category->title ?? '' }}
                            </td>
                            <td>
                                
                                @can('category_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.categories.edit', $category->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('category_delete')
                                    <form action="{{ route('admin.categories.destroy', $category->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('category_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.categories.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Permission:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection